name: "Podcast Generator"
author: "lukamath"
description: "Generates a feed for a podcast from YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git_branch"
  color: "red"
inputs:
  email:
    descriprion: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name: 
    description: The commiter's name
    required: true  
    default: ${{ github.actor }}

